version: "3.9"
services:
    grad_calc_1:
        image: grad_calc:1
        ports: 
            - "8080:8080"
        command: 32 8080
        #volumes:
        #    - ./gc8080_runtime_metrics:/home/dockerc/runtime_metrics
    grad_calc_2:
        image: grad_calc:1
        ports: 
            - "8081:8081"
        command: 32 8081
        #volumes:
        #    - ./gc8081_runtime_metrics:/home/dockerc/runtime_metrics
    grad_calc_3:
        image: grad_calc:1
        ports: 
            - "8082:8082"
        command: 32 8082
        #volumes:
        #    - ./gc8082_runtime_metrics:/home/dockerc/runtime_metrics
    grad_calc_4:
        image: grad_calc:1
        ports: 
            - "8083:8083"
        command: 32 8083
        #volumes:
        #    - ./gc8083_runtime_metrics:/home/dockerc/runtime_metrics
    optimizer:
        image: optimizer:1
        command: "32"
        #volumes:
        #    - ./opt_runtime_metrics:/home/dockerc/runtime_metrics
        depends_on: 
            - grad_calc_1
            - grad_calc_2
            - grad_calc_3
            - grad_calc_4